# these database objects act as a cache for computationally intensive schedule operations
# and are autogenerated.  don't attempt to manipulate them manually.
class ScheduledEventPosition < ActiveRecord::Base
  belongs_to :schedule_block
  belongs_to :event
  validates_uniqueness_of :event_id, :scope => :schedule_block_id
end
